

service: server-vercel
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  timeout: 15
  region: us-east-1 
  memorySize: 2048




functions:
  hello:
    handler: handler.hello
    events:
      - http: ANY /{proxy+}
      - http: ANY /
    environment:
      MONGO_URL: mongodb://Mashael-aljaafari:Mm0559786603@ac-whdx6z2-shard-00-00.2kg4kex.mongodb.net:27017,ac-whdx6z2-shard-00-01.2kg4kex.mongodb.net:27017,ac-whdx6z2-shard-00-02.2kg4kex.mongodb.net:27017/awsDB?ssl=true&replicaSet=atlas-p8f6zt-shard-0&authSource=admin&retryWrites=true&w=majority

      